version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/code/backend
      - ./app/frontend:/code/frontend  # Montar el directorio frontend
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/code/frontend
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metadata
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:


