# Usa una imagen base de Nginx
FROM nginx:alpine

# Establece el directorio de trabajo en /usr/share/nginx/html
# WORKDIR /usr/share/nginx/html

# change working directory
WORKDIR /code/frontend

# Elimina los archivos predeterminados de Nginx
RUN rm -rf ./*

# add frontend code
COPY ./app/frontend /code/frontend

# expose port 3000
EXPOSE 3000







